trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
- task: AzureCLI@2
  inputs:
    azureSubscription: 'KubeSC'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 
- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'KubeSC'
    azureResourceGroup: 'Kube-ProdRg'
    kubernetesCluster: 'farosolutionsprodcluster'
    command: 'apply'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'

