trigger:
- main

pool:
  vmImage: ubuntu-latest


- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'KubeSC'
    azureContainerRegistry: '{"loginServer":"faroprodregistry.azurecr.io", "id" : "/subscriptions/e16a284c-ba7a-4e2f-affa-78fdea4cd5dc/resourceGroups/Kube-ProdRg/providers/Microsoft.ContainerRegistry/registries/faroprodregistry"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'


